### ISSUE TITLE
Banking API error message

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/banking-digitalization-using-hybrid-cloud-with-mainframes#1]
```json
{
  "error": {
    "errorMessage": "URL open: A URL open error occurred when sending the request to the target. 
'http://cap-sg-prd-5.integration.ibmcloud.com:17081/com.ibm.mdm.server.ws.restful/resources/MDMWSRESTful', status  
code: 8. ",
    "errorCode": "0x85800046",
    "errorDescription": "Data cannot be sent to the URL target.",
    "errorSuggestion": "This error can be caused by an external entity (a remote server experiencing  
problems) or an internal issue. Verify that the URL target is correct and that the Content-Type HTTP  
header is appropriate for the data that is being sent. For HTTPS targets, ensure that the validation  
credentials referenced by the SSL client profile or SSL Proxy Profile provided to the URL open()  
function contain the target's server-side certificate or certificate of the immediate issuer. Check the  
log for additional messages on this same transaction for further clarification. Note that the SSL proxy 
 profile is deprecated. Use the SSL client profile with the prefix 'client:'."
  }
}
```

I'm getting this error at the GET /customers/{customer-id} API. The app (html and js) is working fine except the API calls. Curl method and through index.html returns that error instead of the customer data

**Comment by alexis-chretienne** [comment]
Hi @AnthonyAmanse , It is normal. We are migrating some components in the Mainframe. All servers are off.

**Comment by animeshsingh** [comment]
@alexis-chretienne is this error still there? or it was a temporary issue?

**Comment by AnthonyAmanse** [comment]
It was a temporary issue. It was working when I ran it yesterday

**Comment by Dbhatt97** [comment]
This issue is still occuring. is it fixed?

**Comment by NandiniSrinivasOmmi** [comment]
I'm also getting the same error. Can anyone help me

**Comment by pleia2** [comment]
@NandiniSrinivasOmmi Thanks for responding to this issue. This tutorial is from before my time, but I'll take at what may be going on.

If you care to share, how did you come across it? (As I look into this, it'll be helpful to know if/where it's being referenced from)
