### ISSUE TITLE
Pattern needs to be updated

### ISSUE THREAD

**Issue by odrodrig** [IBM/banking-digitalization-using-hybrid-cloud-with-mainframes#7]
After testing the pattern, the following changes are needed:

In Part C step 1. The link to sign up or login in to IBM Cloud doesn’t work.

In Part C step 6-8 need to be updated
- The Getting Started page in IBM Cloud has been changed. There is now no clear way to download or clone the project files.
    - Need to add step for instructions on cloning the project
        - Git clone https://github.com/IBM-Cloud/get-started-node.git
        - Files go into the ‘views’ folder instead of ‘public’
        - Edit html/js/css files as shown
        - Edit Manifest file
            - Change app name
            - Delete the random route line
        - Change the “cf push” to “bx app push”

In Part C step 2. Might need more clarification on where to go in the catalog to find “SDK for Node.js”

In the app the phrase "IBM Developer Journey" is used as the site title and copyright. These should be changed to IBM Code Pattern.

**Comment by stowellme** [comment]
I have updated Part C step 1 - contacted developer to update the other pieces.

**Comment by alexis-chretienne** [comment]
![image](https://user-images.githubusercontent.com/5709384/40413517-49cc91bc-5e76-11e8-9929-92fc8ba42764.png)

@odrodrig , Why I cannot update ??

I updated my other Code Pattern without any problem ! https://github.com/IBM/financial-risk-management-using-machine-learning-on-mainframes

**Comment by alexis-chretienne** [comment]
@odrodrig , I fixed this. I forgot to pull before the push ...

I updated the doc.

**Comment by mattcousens** [comment]
There are still things to be fixed but closing this out since it's partially completed
